version: '2'

services:
    db:
        image: mysql
        volumes:
            - "../.data/db:/var/lib/mysql"
        env_file:
            - ../.env
        environment:
            MYSQL_ROOT_PASSWORD: symfony
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - db
        depends_on:
            - db
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached